[package]
name = "async-sqlx-session"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[features]
default = ["sqlite"]
sqlite = ["sqlx/sqlite"]

[dependencies]
async-session = "2.0.0"
sqlx = { version = "0.3.5" }
async-std = "1.6.2"


[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
